# Generated by Django 3.0.5 on 2021-02-28 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('release_year', models.DateField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=100, verbose_name='Модель')),
                ('engine', models.FloatField(verbose_name='Объем двигателя')),
                ('hp', models.IntegerField(verbose_name='Лошадиные силы')),
                ('gearbox', models.CharField(max_length=100, verbose_name='Коробка')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'db_table': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rent_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('rent_date', models.DateField(verbose_name='Дата бронирования')),
                ('rent_from', models.DateField(verbose_name='Начало аренды')),
                ('rent_till', models.DateField(verbose_name='Конец аренды')),
                ('total_price', models.FloatField(verbose_name='Стоимость аренды')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.Cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'db_table': 'Rent',
            },
        ),
    ]
