# Generated by Django 3.0.5 on 2021-02-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20210228_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='rent_date',
            field=models.DateField(blank=True, verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='total_price',
            field=models.FloatField(blank=True, verbose_name='Стоимость аренды'),
        ),
    ]
