# Generated by Django 3.1.7 on 2021-03-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20210228_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Car_with_Driver-Silhouette.svg/1200px-Car_with_Driver-Silhouette.svg.png', max_length=200, verbose_name='Изображение'),
        ),
    ]
